### ISSUE TITLE
Most SGM ROMs don't work

### ISSUE THREAD

**Issue by goldenegg** [MiSTer-devel/ColecoAdam_MiSTer#10]
Tried to run some SGM ROMs in this core and most don't work. I set the core to console mode and RAM size to SGM.  Most bring up the standard "Turn game off before inserting cartridge or expansion module" screen, while others (which have been programmed to look for the SGM on boot) display an error that the SGM isn't found.

All ROMs I tried were distributed from Pixelboy and all the ROMs work without issue on the standard ColecoVision core.

The following ROMs do not work:

- Buck Rogers
- Caos Begins
- Dragon's Lair
- Children of the Night
- Deep Dungeon Adventure
- Gauntlet
- Ghostbusters
- Goonies
- King and Balloon
- Knights Valley
- Knightmare (Might also have other problems)
- Majikazo
- Mappy
- Mecha9
- Mecha 8
- Operation Wolf (WORKS)
- Qbigs
- RallyX
- Secret of the Moat
- Spelunker
- Stone of Wisdom
- Stray Cat (Works)
- Subroc Super Game
- Thexder (Might have other issues, odd resolution)
- Twinbee (Might have other issues, odd resolution)
- Iridium
- Wizard of Wor
- Zaxxon Super Game
- Zombie Incident

The following ROMs work:

- Cold Blood (Works)
- Danger Tower (WORKS)
- Heroes Arena (WORKS)
- Jetpac (WORKS)
- Knight Lore (WORKS)
- Operation Wolf (WORKS)
- Shump Collection (WORKS)
- Shouganai (Works)
- Stray Cat (Works)
- Super Pac-Man (Works)
- Traffic Jam (Works)
- Txupinazo (Works)

**Comment by goldenegg** [comment]
Just figured out that the games that do work support being played on an Adam computer without an SGM. The games that don't work require the SGM.

**Comment by rampa069** [comment]
As far as i know (dont have the schematics) the SGM module adds 32k RAM and an AY-3 PSG. ADAM has the 32K ram. may be they need the PSG?

**Comment by goldenegg** [comment]
My understanding of the SGM setting for the RAM size option is that it enables support for both the extra RAM and the PSG. The regular Coleco core appears to properly support this, but the Adam version doesn't.

**Comment by rampa069** [comment]
thats it. I stripped all the SGM support due to clashing with adam RAM pagination. Not sure if the SGM is compatible with adam..... I'm going to try to add the AY and see if it works.

**Comment by goldenegg** [comment]
I've never tried connecting the SGM to an Adam, but the box for the SGM says it's compatible.

**Comment by rampa069** [comment]
You were right, i was confused with the SGM module and the SG1000 console... they are compatible and they work

**Comment by rampa069** [comment]
Some carts in still not working, but may be for rom paging system, i'll open another issue with them and will investigate each one.

**Comment by rampa069** [comment]
to be continued in #12

**Comment by goldenegg** [comment]
With the exception of Uridium, this has been resolved. The Uridium issue shouldn't be tracked with this ticket.
