### ISSUE TITLE
Donkey Kong Junior Super Game (1984) freezes

### ISSUE THREAD

**Issue by mrfpga** [MiSTer-devel/ColecoAdam_MiSTer#2]
Donkey Kong Junior Super Game (1984) locks up each time when Junior reaches Mario's Hideout and performs the first jump to the lower platform in the middle. The screen freezes and the sound continues to play, but there is no way to continue.

The bug is present in both releases ColecoAdam_20220521.rbf and ColecoAdam_20220519.rbf

I tried three different dumps (obtained from adamarchive.org), but the problem persists:

- Donkey Kong Junior Super Game (1984) (Coleco).dsk (CRC32: CFA4F6C7)
- Donkey Kong Junior Super Game (1984) (Coleco) (5 Screen Rev. 14 Prototype).dsk (CRC32: 9880CF54)
- Donkey Kong Junior Super Game (1984) (Coleco) (5 Screen Rev. 14 Prototype).ddp (CRC32: 61C762D7)

For testing purposes I set the difficulty to 1 to make it easier to advance to Mario's Hideout.

Here is a screenshot for reference not taken from MiSTer, but from Youtube:
https://s20.directupload.net/images/220522/rhf74ivs.jpg

UPDATE: The bug is also present in the newest release ColecoAdam_20220522.rbf

**Comment by rampa069** [comment]
can you please test in the actual release 20220523? i have been working on same parts that can fix this problem. Thanks!

**Comment by mrfpga** [comment]
Thank you for the update. I can confirm that the issue is now fixed with release 20220523.

**Comment by rampa069** [comment]
fixed in #6
