### ISSUE TITLE
Music in Dragon's Lair has incorrect bass

### ISSUE THREAD

**Issue by goldenegg** [MiSTer-devel/ColecoAdam_MiSTer#3]
When playing Dragon's Lair (DDP), the music is quite a bit off from the original when bass frequencies are used.

**Comment by rampa069** [comment]
please test the last release. i dont have the original but comparing with youtube sounds quite similar.

**Comment by goldenegg** [comment]
Still the same problem with the May 23rd release. The regular Coleco core has the same problem. It's not only Dragon's Lair that's affected. You can see the reported issue here https://github.com/MiSTer-devel/ColecoVision_MiSTer/issues/2

**Comment by rampa069** [comment]
Thank you very much... in this videos i can listen the problem.  i'm going to investigate.

**Comment by goldenegg** [comment]
Thanks. I'll also try to get you a better recording of the Dragon's Lair audio. It'll be a day or two before I can get my Adam out.

**Comment by rampa069** [comment]
I think i have it now. Can you please test this core before pushing it to the official repo? 

https://github.com/rampa069/ColecoAdam_MiSTer/raw/master/releases/ColecoAdam_20220524.rbf

If everythink is ok, i'll push the changes also to the Colecovision repo.

**Comment by goldenegg** [comment]
YES!!!! That sounds great! Thank you so much!

**Comment by goldenegg** [comment]
This is working in the release build. Closing this issue.
