### ISSUE TITLE
Choplifter gfx issues

### ISSUE THREAD

**Issue by skosh70** [MiSTer-devel/ColecoAdam_MiSTer#7]
Choplifter has corrupt gfx when shooting tanks and other rendering issues. Bullets and other objects appear as lines.
![Choplifter](https://user-images.githubusercontent.com/106125167/169925553-c24967fa-7319-4032-b139-0b75b1f805ea.png)
![choplifter 2](https://user-images.githubusercontent.com/106125167/169925556-3af1ba1c-3e86-45fb-8ad0-17d2fe63fb7c.png)

**Comment by rampa069** [comment]
can't reproduce :(

 Which core date are you using? where can i get the same cart as you?

**Comment by skosh70** [comment]
I tried it with 2 different roms from old TOSEC and No-Intro sets. I went to Atariage and downloaded the latest Coleco set and Choplifter from there works perfect. So no issue beside me using a bad rom.  So no issue and sorry for the distraction. :)
